name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Or 'main' if that is the name of your default branch

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Ensure Ruby 3.0 is installed

      - name: Update RubyGems
        run: gem update --system

      - name: Install Bundler
        run: gem install bundler -v '2.3.0'  # Use a compatible version of bundler with Ruby 3.0

      - name: Install Dependencies
        run: bundle install

      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          JEKYLL_ENV: production  # Specify the environment for Jekyll
