name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Or 'main' if that is the name of your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'

      - name: Install Bundler
        run: gem install bundler -v '2.3.0'

      - name: Install Dependencies
        run: bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # The directory where Jekyll outputs the site
          publish_branch: gh-pages  # The branch to which the site should be deployed
