name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Or 'main' if that is the name of your default branch

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bundler
        run: gem install bundler -v '2.3.0'

      - name: Install Dependencies
        run: bundle install

      - name: Build and Deploy
        uses: joshdholtz/jekyll-deploy-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: master
          branch: gh-pages
          jekyll_src: './'
